

# This file was *autogenerated* from the file bls12_381.sage
from sage.all_cmdline import *   # import sage library

_sage_const_52435875175126190479447740508185965837690552500527637822603658699938581184513 = Integer(52435875175126190479447740508185965837690552500527637822603658699938581184513); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_256 = Integer(256); _sage_const_512 = Integer(512); _sage_const_768 = Integer(768); _sage_const_7 = Integer(7); _sage_const_32 = Integer(32); _sage_const_4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787 = Integer(4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787); _sage_const_384 = Integer(384); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)# --------------- fr.rs ----------------

# 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001
SUBGROUP_SIZE_R = _sage_const_52435875175126190479447740508185965837690552500527637822603658699938581184513 
print(f"{SUBGROUP_SIZE_R = }")
print(f"{hex(SUBGROUP_SIZE_R) = }")

INV_q = -(SUBGROUP_SIZE_R**-_sage_const_1  % _sage_const_2 **_sage_const_64 ) % _sage_const_2 **_sage_const_64 
print(f"{INV_q = }")
print(f"{hex(INV_q) = }")

R_r = _sage_const_2 **_sage_const_256  % SUBGROUP_SIZE_R
print(f"{R_r = }")
print(f"{hex(R_r) = }")

R2_r = _sage_const_2 **_sage_const_512  % SUBGROUP_SIZE_R
print(f"{R2_r = }")
print(f"{hex(R2_r) = }")

R3_r = _sage_const_2 **_sage_const_768  % SUBGROUP_SIZE_R
print(f"{R3_r = }")
print(f"{hex(R3_r) = }")

GENERATOR_r = _sage_const_7  % SUBGROUP_SIZE_R
print(f"{GENERATOR_r = }")
print(f"{hex(GENERATOR_r) = }")

S_r = _sage_const_32 
t_r = (SUBGROUP_SIZE_R - _sage_const_1 ) / (_sage_const_2 **S_r)
print(f"{t_r = }")
print(f"{hex(t_r) = }")

# Following gives error OverflowError: exponent must be at most 9223372036854775807
# ROOT_OF_UNITY = GENERATOR ** ((SUBGROUP_SIZE_R - 1) / 2 ** S)
# ROOT_OF_UNITY = pow(GENERATOR,((SUBGROUP_SIZE_R - 1) / 2 ** S))
# print(f"{ROOT_OF_UNITY = }")
# print(f"{hex(ROOT_OF_UNITY) = }")

# --------------- fq.rs ----------------

# 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab
FIELD_MODULUS_Q = _sage_const_4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787 

print("FIELD_MODULUS_Q: ", FIELD_MODULUS_Q)
print("FIELD_MODULUS_Q (hex): ", hex(FIELD_MODULUS_Q))

INV_q = -(FIELD_MODULUS_Q**-_sage_const_1  % _sage_const_2 **_sage_const_64 ) % _sage_const_2 **_sage_const_64 
print(f"{INV_q = }")
print(f"{hex(INV_q) = }")

R_q = _sage_const_2 **_sage_const_384  % FIELD_MODULUS_Q
print(f"{R_q = }")
print(f"{hex(R_q) = }")

R2_q = R_q**_sage_const_2  % FIELD_MODULUS_Q
print(f"{R2_q = }")
print(f"{hex(R2_q) = }")

R3_q = R_q**_sage_const_3  % FIELD_MODULUS_Q
print(f"{R3_q = }")
print(f"{hex(R3_q) = }")

NEGATIVE_ONE_q = -((_sage_const_2 **_sage_const_384 ) % FIELD_MODULUS_Q) % FIELD_MODULUS_Q
print(f"{NEGATIVE_ONE_q = }")
print(f"{hex(NEGATIVE_ONE_q) = }")

TWO_INV_q = _sage_const_2 **(-_sage_const_1 ) % FIELD_MODULUS_Q
print(f"{TWO_INV_q = }")
print(f"{hex(TWO_INV_q) = }")

LEGENDRE = (FIELD_MODULUS_Q - _sage_const_1 ) / _sage_const_2 
print(f"{LEGENDRE = }")
print(f"{hex(LEGENDRE) = }")

SQRT_Q_PLUS_1_DIV_4 = (FIELD_MODULUS_Q + _sage_const_1 ) / _sage_const_4 
print(f"{SQRT_Q_PLUS_1_DIV_4 = }")
print(f"{hex(SQRT_Q_PLUS_1_DIV_4) = }")

SQRT_Q_MIN_3_DIV_4 = (FIELD_MODULUS_Q - _sage_const_3 ) / _sage_const_4 
print(f"{SQRT_Q_MIN_3_DIV_4 = }")
print(f"{hex(SQRT_Q_MIN_3_DIV_4) = }")

Q_MIN_2 = (FIELD_MODULUS_Q - _sage_const_2 ) 
print(f"{Q_MIN_2 = }")
print(f"{hex(Q_MIN_2) = }")

